### ISSUE TITLE
Possible to leave LED on when key pressed?

### ISSUE THREAD

**Issue by Drudoo** [TheDiveO/multibow#1]
Is it possible to make all the LEDs stay on when you press a key?

**Comment by thediveo** [comment]
In principle yes, but not with the current main version. Would you like to change this behavior for all keys or only for certain keys?

**Comment by Drudoo** [comment]
Probably for all keys. It just seems weird to me that they blink/flashes when pressed.

**Comment by thediveo** [comment]
The blinking is due to the Kdenlive layout needing to do some keypresses repeatedly with a certain "slowness". However, I clearly see reason to disable it in many other situations.

**Comment by thediveo** [comment]
Project is archived.
